CREATE DATABASE HotelHease;

USE HotelHease;

CREATE TABLE Hotel(
	ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CNPJ VARCHAR(20) NOT NULL UNIQUE,
	Nome VARCHAR(50) NOT NULL,
	Capacidade INT(10) NOT NULL CHECK(Capacidade > 0)
);

CREATE TABLE HotelEndereco(
	ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FkHotel INT(11) NOT NULL,
	Rua VARCHAR(30) NOT NULL,
	Numero INT(8) NOT NULL CHECK(Numero > 0),
	Bairro VARCHAR(30) NOT NULL,
	Cidade VARCHAR(20) NOT NULL,
	Estado VARCHAR(20) NOT NULL,
	Cep CHAR(10),
	FOREIGN KEY(FkHotel) REFERENCES Hotel(ID)
);

CREATE TABLE HotelContato(
	ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FkHotel INT(11) NOT NULL,
	Email VARCHAR(30),
	Telefone VARCHAR(20),
	FOREIGN KEY(FkHotel) REFERENCES Hotel(ID)
);

CREATE TABLE Quarto(
	ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FkHotel INT(11) NOT NULL,
	Categoria VARCHAR(10) NOT NULL CHECK(Categoria IN ('Standard', 'Master', 'Deluxe')),
	Numero INT(6) NOT NULL,
	Status VARCHAR(10) NOT NULL CHECK(Status IN('Disponível', 'Ocupado', 'Manutenção')),
	FOREIGN KEY(FkHotel) REFERENCES Hotel(ID),
	UNIQUE(FkHotel, Numero)
);

CREATE TABLE Pessoa(
	ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CPF CHAR(14) UNIQUE,
	PrimeiroNome VARCHAR(30) NOT NULL,
	NomeMeio VARCHAR(30),
	UltimoNome VARCHAR(30)
);
	
CREATE TABLE PessoaEndereco(
	ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FkPessoa INT(11) NOT NULL,
	Rua VARCHAR(30) NOT NULL,
	Numero CHAR(8),
	Bairro VARCHAR(30) NOT NULL,
	Cidade VARCHAR(20) NOT NULL,
	Estado VARCHAR(20) NOT NULL,
	Cep CHAR(10),
	FOREIGN KEY(FkPessoa) REFERENCES Pessoa(ID)
);

CREATE TABLE PessoaContato(
	ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FkPessoa INT(11) NOT NULL,
	Email VARCHAR(30) UNIQUE,
	Telefone VARCHAR(20),
	FOREIGN KEY(FkPessoa) REFERENCES Pessoa(ID)
);

CREATE TABLE Hospede(
	FkPessoa INT(11) NOT NULL PRIMARY KEY,
	FOREIGN KEY(FkPessoa) REFERENCES Pessoa(ID)
);

CREATE TABLE Funcionario(
	FkPessoa INT(11) NOT NULL PRIMARY KEY,
	FkHotel INT(11) NOT NULL,
	Funcao VARCHAR(50) NOT NULL,
	FOREIGN KEY(FkPessoa) REFERENCES Pessoa(ID),
	FOREIGN KEY(FkHotel) REFERENCES Hotel(ID)
);

CREATE TABLE Reserva(
	ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DataCheckIn DATE NOT NULL,
	DataCheckOut DATE NOT NULL,
	ValorPago DOUBLE(8, 2) 	NOT NULL,
	Status VARCHAR(15) NOT NULL CHECK(Status IN('Em andamento', 'Concluída', 'Cancelada')),
	FkHotel INT(11) NOT NULL,
	FkQuarto INT(11) NOT NULL,
	FkHospede INT(11) NOT NULL,
	FOREIGN KEY(FkHotel) REFERENCES Hotel(ID),
	FOREIGN KEY(FkQuarto) REFERENCES Quarto(ID),
	FOREIGN KEY(FkHospede) REFERENCES Hospede(FkPessoa)
);

CREATE TABLE ServicoAdicional(
	ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NomeServico VARCHAR(60) NOT NULL,
	Descricao TEXT,
	Preco DOUBLE(8, 2) NOT NULL
);

CREATE TABLE Contrata(
	FkReserva INT(11) NOT NULL,
	FkServicoAdicional INT(11) NOT NULL,
	PRIMARY KEY (FkReserva, FkServicoAdicional),
	FOREIGN KEY(FkReserva) REFERENCES Reserva(ID),
	FOREIGN KEY(FkServicoAdicional) REFERENCES ServicoAdicional(ID)
);



